"""empty message

Revision ID: 957310e19cd9
Revises: d0f9192aa5b6
Create Date: 2024-04-05 22:17:53.675870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '957310e19cd9'
down_revision = 'd0f9192aa5b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
